2021-01-30 14:05:06,053 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 109086ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 14:09:12,513 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 206433ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 16:39:49,450 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 441664ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 16:43:27,737 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 177300ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 17:15:56,744 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 68536ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 21:33:00,681 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 301332ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 21:38:48,675 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 307240ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 21:40:40,707 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 71260ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 21:43:08,516 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 107044ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 21:45:32,557 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 103297ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 21:48:18,157 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 60720ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 21:54:05,625 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 307424ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 21:59:52,601 ERROR 86438 nodejs.ClusterClientNoResponseError: client no response in 306969ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 86438
hostname: xiejialis-MacBook-Pro.local

2021-01-30 22:55:33,204 ERROR 14055 [-/127.0.0.1/-/18ms PUT /api/v1/postAd] nodejs.InternalServerError: Missing required parameters!
    at Object.throw (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/koa/lib/context.js:97:11)
    at AdvertiseController.postAd (/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/controller/advertise.js:25:50)
    at Object.callFn (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-core/lib/utils/index.js:44:21)
    at Object.classControllerMiddleware (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-core/lib/loader/mixin/controller.js:87:20)
    at Object.callFn (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/@eggjs/router/lib/utils.js:12:21)
    at wrappedController (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/@eggjs/router/lib/egg_router.js:322:18)
    at dispatch (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/koa-compose/index.js:44:32)
    at next (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/koa-compose/index.js:45:18)
    at /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/@eggjs/router/lib/router.js:190:18
    at dispatch (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/koa-compose/index.js:44:32)
message: "Missing required parameters!"
headers: {"Access-Control-Allow-Origin":"*","vary":"Origin"}
pid: 14055
hostname: xiejialis-MacBook-Pro.local

