2021-02-02 01:00:09,133 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 94771ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 01:07:31,454 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 402145ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 01:28:45,095 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 1228615ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 01:44:52,102 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 917890ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 03:45:40,136 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 7204055ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 04:28:53,097 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 2550300ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 05:14:41,611 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 2706004ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 05:59:34,956 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 2646594ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 06:56:35,642 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 3378006ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-02 07:11:09,943 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 830856ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

