2020-12-23 11:33:35,252 ERROR 63424 nodejs.ClusterClientNoResponseError: client no response in 34332478ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 63424
hostname: xiejialis-MacBook-Pro.local

2021-01-05 10:56:10,180 ERROR 77310 nodejs.ClusterClientNoResponseError: client no response in 70429ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 77310
hostname: xiejialis-MacBook-Pro.local

2021-01-05 11:08:18,315 ERROR 78372 nodejs.SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async ConnectionManager._connect (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
    at async ConnectionManager.getConnection (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
    at async /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/sequelize.js:613:26
    at async Sequelize.authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/sequelize.js:867:5)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:134:7)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:142:7)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:142:7)
name: "SequelizeConnectionRefusedError"
parent: {"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}
original: {"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}
pid: 78372
hostname: xiejialis-MacBook-Pro.local

2021-01-05 11:19:58,656 ERROR 78773 nodejs.SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306
    at ConnectionManager.connect (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:116:17)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async ConnectionManager._connect (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
    at async ConnectionManager.getConnection (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
    at async /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/sequelize.js:613:26
    at async Sequelize.authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/sequelize.js:867:5)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:134:7)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:142:7)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:142:7)
name: "SequelizeConnectionRefusedError"
parent: {"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}
original: {"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}
pid: 78773
hostname: xiejialis-MacBook-Pro.local

2021-01-05 14:04:04,210 ERROR 3998 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at ConnectionManager.connect (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async ConnectionManager._connect (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
    at async ConnectionManager.getConnection (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
    at async /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/sequelize.js:613:26
    at async Sequelize.authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/sequelize.js:867:5)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:134:7)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:142:7)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:142:7)
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 3998
hostname: xiejialis-MacBook-Pro.local

2021-01-05 14:06:45,984 ERROR 4078 nodejs.SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: NO)
    at ConnectionManager.connect (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:118:17)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async ConnectionManager._connect (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:318:24)
    at async /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:250:32
    at async ConnectionManager.getConnection (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:280:7)
    at async /Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/sequelize.js:613:26
    at async Sequelize.authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/sequelize/lib/sequelize.js:867:5)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:134:7)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:142:7)
    at async authenticate (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/egg-sequelize/lib/loader.js:142:7)
name: "SequelizeAccessDeniedError"
parent: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
original: {"code":"ER_ACCESS_DENIED_ERROR","errno":1045,"sqlState":"28000","sqlMessage":"Access denied for user 'root'@'localhost' (using password: NO)"}
pid: 4078
hostname: xiejialis-MacBook-Pro.local

