2020-12-22 05:41:23,977 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 16878865ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 08:26:09,840 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 9845535ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 08:42:48,994 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 919113ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 09:02:45,773 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 1156763ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 09:17:49,628 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 843045ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 09:28:26,116 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 596462ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 09:33:05,610 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 239460ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 09:36:01,416 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 135031ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 09:42:46,006 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 184516ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 10:07:41,545 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 1475498ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 10:17:35,330 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 118709ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 10:44:05,876 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 1262742ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 11:11:40,107 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 753320ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 11:24:03,082 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 701458ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 11:25:53,719 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 70594ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 11:40:55,898 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 861411ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 11:55:59,639 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 862232ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 12:11:01,897 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 862233ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 12:40:34,717 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 252543ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 12:57:36,861 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 141217ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 13:06:57,633 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 520004ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 13:57:53,547 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 294076ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 14:39:55,324 ERROR 63424 nodejs.ClusterClientNoResponseError: client no response in 2415292ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 63424
hostname: xiejialis-MacBook-Pro.local

2020-12-22 14:45:17,967 ERROR 63424 nodejs.ClusterClientNoResponseError: client no response in 262601ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 63424
hostname: xiejialis-MacBook-Pro.local

2020-12-22 15:00:19,937 ERROR 63424 nodejs.ClusterClientNoResponseError: client no response in 861930ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 63424
hostname: xiejialis-MacBook-Pro.local

2020-12-22 15:15:21,943 ERROR 63424 nodejs.ClusterClientNoResponseError: client no response in 861968ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 63424
hostname: xiejialis-MacBook-Pro.local

2020-12-22 15:31:11,640 ERROR 63424 nodejs.ClusterClientNoResponseError: client no response in 909472ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 63424
hostname: xiejialis-MacBook-Pro.local

2020-12-22 16:59:38,205 ERROR 63424 nodejs.ClusterClientNoResponseError: client no response in 5266450ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 63424
hostname: xiejialis-MacBook-Pro.local

2020-12-23 02:00:41,799 ERROR 63424 nodejs.ClusterClientNoResponseError: client no response in 32462186ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 63424
hostname: xiejialis-MacBook-Pro.local

