2020-12-21 00:00:01,299 INFO 37329 [egg-logrotator] agent logger reload: got log-reload message
2020-12-21 01:21:04,856 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 1365767ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 01:29:33,137 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 467599ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 01:45:56,907 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 941014ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 02:57:02,914 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 4225234ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 04:52:45,026 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 6901226ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 05:35:02,365 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 2493355ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 06:55:52,128 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 4808955ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 07:37:27,343 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 2455118ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 09:30:13,912 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 6726294ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 09:36:05,809 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 310483ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 09:52:42,183 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 846599ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 10:04:54,813 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 692197ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 10:12:04,848 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 389425ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 10:42:34,981 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 229429ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 12:37:18,719 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 1641487ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 16:45:28,697 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 247356ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 16:51:29,588 ERROR 37329 nodejs.ClusterClientNoResponseError: client no response in 320824ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 37329
hostname: xiejialis-MacBook-Pro.local

2020-12-21 17:36:13,660 INFO 57644 [egg:logger] init all loggers with options: {"dir":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/logs/petcity-back","encoding":"utf8","env":"local","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":false,"outputJSON":false,"buffer":true,"appLogName":"petcity-back-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{"consoleLevel":"WARN"},"allowDebugAtProd":false,"type":"agent"}
2020-12-21 17:36:13,669 INFO 57644 [egg:core] dump config after load, 6ms
2020-12-21 17:36:13,705 INFO 57644 [egg-watcher] Start watching: ["/Users/sherily/Desktop/Petcity/Repo/petcity-back/app","/Users/sherily/Desktop/Petcity/Repo/petcity-back/config","/Users/sherily/Desktop/Petcity/Repo/petcity-back/mocks","/Users/sherily/Desktop/Petcity/Repo/petcity-back/mocks_proxy","/Users/sherily/Desktop/Petcity/Repo/petcity-back/app.js"]
2020-12-21 17:36:13,705 INFO 57644 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/app"
2020-12-21 17:36:13,705 INFO 57644 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/config"
2020-12-21 17:36:13,705 INFO 57644 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/mocks"
2020-12-21 17:36:13,705 INFO 57644 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/mocks_proxy"
2020-12-21 17:36:13,706 INFO 57644 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/app.js"
2020-12-21 17:36:13,706 INFO 57644 [egg-watcher:agent] watcher start success
2020-12-21 17:36:13,718 INFO 57644 [egg:core] dump config after ready, 2ms
2020-12-21 17:38:41,674 WARN 57644 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.local.js rename
2020-12-21 17:38:41,468 INFO 57644 [egg-watcher] Received a change event from eventSource: {"event":"rename","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.local.js","stat":{"dev":16777223,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365879,"size":0,"blocks":0,"atimeMs":1608525521402.2917,"mtimeMs":1608525521402.2917,"ctimeMs":1608525521402.2917,"birthtimeMs":1608525521402.2917,"atime":"2020-12-21T04:38:41.402Z","mtime":"2020-12-21T04:38:41.402Z","ctime":"2020-12-21T04:38:41.402Z","birthtime":"2020-12-21T04:38:41.402Z"},"remove":false,"isDirectory":false,"isFile":true}
2020-12-21 17:38:55,907 WARN 57644 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.prod.js rename
2020-12-21 17:38:55,702 INFO 57644 [egg-watcher] Received a change event from eventSource: {"event":"rename","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.prod.js","stat":{"dev":16777223,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365900,"size":0,"blocks":0,"atimeMs":1608525535689.9343,"mtimeMs":1608525535689.9343,"ctimeMs":1608525535689.9343,"birthtimeMs":1608525535689.9343,"atime":"2020-12-21T04:38:55.690Z","mtime":"2020-12-21T04:38:55.690Z","ctime":"2020-12-21T04:38:55.690Z","birthtime":"2020-12-21T04:38:55.690Z"},"remove":false,"isDirectory":false,"isFile":true}
2020-12-21 17:39:22,492 WARN 57644 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js change
2020-12-21 17:39:22,290 INFO 57644 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js","stat":{"dev":16777223,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23326796,"size":402,"blocks":8,"atimeMs":1608525345512.6392,"mtimeMs":1608525562229.4478,"ctimeMs":1608525562229.4478,"birthtimeMs":1608449805534.0703,"atime":"2020-12-21T04:35:45.513Z","mtime":"2020-12-21T04:39:22.229Z","ctime":"2020-12-21T04:39:22.229Z","birthtime":"2020-12-20T07:36:45.534Z"},"remove":false,"isDirectory":false,"isFile":true}
2020-12-21 17:44:04,987 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 187961ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-21 17:59:06,400 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 861369ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-21 18:14:08,396 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 861970ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-21 18:21:44,732 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 416304ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-21 18:37:35,716 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 909327ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

2020-12-22 01:00:05,089 ERROR 57644 nodejs.ClusterClientNoResponseError: client no response in 22908545ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 57644
hostname: xiejialis-MacBook-Pro.local

