2021-02-01 00:00:01,199 INFO 43274 [egg-logrotator] agent logger reload: got log-reload message
2021-02-01 00:09:10,932 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 310136ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 00:31:49,059 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 1317965ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 01:16:13,141 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 2624035ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 01:31:25,828 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 872647ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 01:49:55,156 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 979619ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 03:37:38,905 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 6422972ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 04:26:09,175 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 2750180ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 04:34:16,851 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 447570ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 06:38:02,817 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 63500ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 06:40:21,359 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 98451ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 07:06:18,974 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 1455197ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 08:02:56,192 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 315816ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 08:17:57,506 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 874783ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 08:32:59,258 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 860218ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 08:46:36,922 ERROR 43274 nodejs.ClusterClientNoResponseError: client no response in 777626ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 43274
hostname: xiejialis-MacBook-Pro.local

2021-02-01 09:20:45,270 INFO 55806 [egg-sequelize](1ms) Executed (default): SELECT 1+1 AS result
2021-02-01 09:20:44,826 INFO 55806 [egg:logger] init all loggers with options: {"dir":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/logs/petcity-back","encoding":"utf8","env":"local","level":"INFO","consoleLevel":"INFO","disableConsoleAfterReady":false,"outputJSON":false,"buffer":true,"appLogName":"petcity-back-web.log","coreLogName":"egg-web.log","agentLogName":"egg-agent.log","errorLogName":"common-error.log","coreLogger":{"consoleLevel":"WARN"},"allowDebugAtProd":false,"type":"agent"}
2021-02-01 09:20:45,174 INFO 55806 [egg-alinode] alinode agentx started, node versions: {"node":"15.4.0","v8":"8.6.395.17-node.22","uv":"1.40.0","zlib":"1.2.11","brotli":"1.0.9","ares":"1.16.1","modules":"88","nghttp2":"1.41.0","napi":"7","llhttp":"2.1.3","openssl":"1.1.1g","cldr":"38.0","icu":"68.1","tz":"2020b","unicode":"13.0"}, update /Users/sherily/.nodepath with "/usr/local/bin", config: {"server":"wss://agentserver.node.aliyun.com:8080","appid":"87325"}
2021-02-01 09:20:45,178 INFO 55806 [egg:core] dump config after load, 4ms
2021-02-01 09:20:45,225 INFO 55806 [egg-watcher] Start watching: ["/Users/sherily/Desktop/Petcity/Repo/petcity-back/app","/Users/sherily/Desktop/Petcity/Repo/petcity-back/config","/Users/sherily/Desktop/Petcity/Repo/petcity-back/mocks","/Users/sherily/Desktop/Petcity/Repo/petcity-back/mocks_proxy","/Users/sherily/Desktop/Petcity/Repo/petcity-back/app.js"]
2021-02-01 09:20:45,225 INFO 55806 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/app"
2021-02-01 09:20:45,225 INFO 55806 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/config"
2021-02-01 09:20:45,226 INFO 55806 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/mocks"
2021-02-01 09:20:45,226 INFO 55806 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/mocks_proxy"
2021-02-01 09:20:45,226 INFO 55806 [egg-watcher] Start watching: "/Users/sherily/Desktop/Petcity/Repo/petcity-back/app.js"
2021-02-01 09:20:45,226 INFO 55806 [egg-watcher:agent] watcher start success
2021-02-01 09:20:45,277 INFO 55806 [egg:core] dump config after ready, 6ms
2021-02-01 10:17:14,746 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 532606ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 10:20:44,754 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 169149ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 10:47:14,285 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 1329167ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 13:10:20,041 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 463024ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 13:23:48,115 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 686324ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 13:28:12,977 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 224281ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 15:41:26,952 WARN 55806 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js change
2021-02-01 15:41:26,696 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365671,"size":492,"blocks":8,"atimeMs":1611218941643.079,"mtimeMs":1612147286572.4119,"ctimeMs":1612147286572.4119,"birthtimeMs":1608525281353.2979,"atime":"2021-01-21T08:49:01.643Z","mtime":"2021-02-01T02:41:26.572Z","ctime":"2021-02-01T02:41:26.572Z","birthtime":"2020-12-21T04:34:41.353Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 15:44:24,270 WARN 55806 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js change
2021-02-01 15:44:24,068 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365671,"size":492,"blocks":8,"atimeMs":1612147289057.7053,"mtimeMs":1612147464005.9617,"ctimeMs":1612147464005.9617,"birthtimeMs":1608525281353.2979,"atime":"2021-02-01T02:41:29.058Z","mtime":"2021-02-01T02:44:24.006Z","ctime":"2021-02-01T02:44:24.006Z","birthtime":"2020-12-21T04:34:41.353Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 15:44:24,361 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365671,"size":492,"blocks":8,"atimeMs":1612147289057.7053,"mtimeMs":1612147464354.46,"ctimeMs":1612147464354.46,"birthtimeMs":1608525281353.2979,"atime":"2021-02-01T02:41:29.058Z","mtime":"2021-02-01T02:44:24.354Z","ctime":"2021-02-01T02:44:24.354Z","birthtime":"2020-12-21T04:34:41.353Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 15:44:24,463 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365671,"size":492,"blocks":8,"atimeMs":1612147289057.7053,"mtimeMs":1612147464354.46,"ctimeMs":1612147464354.46,"birthtimeMs":1608525281353.2979,"atime":"2021-02-01T02:41:29.058Z","mtime":"2021-02-01T02:44:24.354Z","ctime":"2021-02-01T02:44:24.354Z","birthtime":"2020-12-21T04:34:41.353Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 15:44:24,643 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365671,"size":492,"blocks":8,"atimeMs":1612147289057.7053,"mtimeMs":1612147464632.861,"ctimeMs":1612147464632.861,"birthtimeMs":1608525281353.2979,"atime":"2021-02-01T02:41:29.058Z","mtime":"2021-02-01T02:44:24.633Z","ctime":"2021-02-01T02:44:24.633Z","birthtime":"2020-12-21T04:34:41.353Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 15:44:24,706 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365671,"size":492,"blocks":8,"atimeMs":1612147289057.7053,"mtimeMs":1612147464632.861,"ctimeMs":1612147464632.861,"birthtimeMs":1608525281353.2979,"atime":"2021-02-01T02:41:29.058Z","mtime":"2021-02-01T02:44:24.633Z","ctime":"2021-02-01T02:44:24.633Z","birthtime":"2020-12-21T04:34:41.353Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 15:44:24,908 WARN 55806 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js change
2021-02-01 15:44:33,715 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365671,"size":492,"blocks":8,"atimeMs":1612147466863.9966,"mtimeMs":1612147473704.079,"ctimeMs":1612147473704.079,"birthtimeMs":1608525281353.2979,"atime":"2021-02-01T02:44:26.864Z","mtime":"2021-02-01T02:44:33.704Z","ctime":"2021-02-01T02:44:33.704Z","birthtime":"2020-12-21T04:34:41.353Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 15:44:33,765 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23365671,"size":492,"blocks":8,"atimeMs":1612147466863.9966,"mtimeMs":1612147473704.079,"ctimeMs":1612147473704.079,"birthtimeMs":1608525281353.2979,"atime":"2021-02-01T02:44:26.864Z","mtime":"2021-02-01T02:44:33.704Z","ctime":"2021-02-01T02:44:33.704Z","birthtime":"2020-12-21T04:34:41.353Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 15:44:33,971 WARN 55806 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/app/middleware/robot.js change
2021-02-01 16:04:07,679 WARN 55806 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js change
2021-02-01 16:04:07,474 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23326796,"size":3655,"blocks":8,"atimeMs":1612086213976.4053,"mtimeMs":1612148647408.209,"ctimeMs":1612148647408.209,"birthtimeMs":1608449805534.0703,"atime":"2021-01-31T09:43:33.976Z","mtime":"2021-02-01T03:04:07.408Z","ctime":"2021-02-01T03:04:07.408Z","birthtime":"2020-12-20T07:36:45.534Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 16:04:07,768 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23326796,"size":0,"blocks":0,"atimeMs":1612086213976.4053,"mtimeMs":1612148647756.7131,"ctimeMs":1612148647756.7131,"birthtimeMs":1608449805534.0703,"atime":"2021-01-31T09:43:33.976Z","mtime":"2021-02-01T03:04:07.757Z","ctime":"2021-02-01T03:04:07.757Z","birthtime":"2020-12-20T07:36:45.534Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 16:04:08,342 WARN 55806 [agent:development] reload worker because /Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js change
2021-02-01 16:04:07,845 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23326796,"size":3655,"blocks":8,"atimeMs":1612086213976.4053,"mtimeMs":1612148647769.8855,"ctimeMs":1612148647769.8855,"birthtimeMs":1608449805534.0703,"atime":"2021-01-31T09:43:33.976Z","mtime":"2021-02-01T03:04:07.770Z","ctime":"2021-02-01T03:04:07.770Z","birthtime":"2020-12-20T07:36:45.534Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 16:04:08,041 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23326796,"size":3655,"blocks":8,"atimeMs":1612086213976.4053,"mtimeMs":1612148648031.1753,"ctimeMs":1612148648031.1753,"birthtimeMs":1608449805534.0703,"atime":"2021-01-31T09:43:33.976Z","mtime":"2021-02-01T03:04:08.031Z","ctime":"2021-02-01T03:04:08.031Z","birthtime":"2020-12-20T07:36:45.534Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 16:04:08,137 INFO 55806 [egg-watcher] Received a change event from eventSource: {"event":"change","path":"/Users/sherily/Desktop/Petcity/Repo/petcity-back/config/config.default.js","stat":{"dev":16777225,"mode":33188,"nlink":1,"uid":501,"gid":20,"rdev":0,"blksize":4096,"ino":23326796,"size":3655,"blocks":8,"atimeMs":1612086213976.4053,"mtimeMs":1612148648031.1753,"ctimeMs":1612148648031.1753,"birthtimeMs":1608449805534.0703,"atime":"2021-01-31T09:43:33.976Z","mtime":"2021-02-01T03:04:08.031Z","ctime":"2021-02-01T03:04:08.031Z","birthtime":"2020-12-20T07:36:45.534Z"},"remove":false,"isDirectory":false,"isFile":true}
2021-02-01 16:46:28,287 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 133902ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 17:01:29,010 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 859739ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 17:16:30,237 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 861189ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 17:24:12,818 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 422532ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 17:33:33,574 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 520367ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 17:45:47,097 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 692731ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 17:51:48,637 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 320736ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 18:06:51,353 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 841922ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 18:21:52,349 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 840210ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 18:36:53,347 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 860224ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 18:43:38,609 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 365216ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 18:45:02,069 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 82587ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 19:01:17,624 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 862613ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 19:18:51,387 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 863017ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 19:36:25,374 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 861032ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 19:53:59,391 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 861279ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 21:25:13,302 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 5280784ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 21:51:54,712 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 1407852ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 22:10:23,056 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 911453ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 22:36:10,551 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 1344312ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 23:10:20,356 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 908663ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

2021-02-01 23:15:27,151 ERROR 55806 nodejs.ClusterClientNoResponseError: client no response in 265960ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/sherily/Desktop/Petcity/Repo/petcity-back/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7)
name: "ClusterClientNoResponseError"
pid: 55806
hostname: xiejialis-MacBook-Pro.local

